// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaSlIBz3WAl9ICRfnfx4dTut-u-tyk0M',
    appId: '1:375357259172:web:c745d2de5cd2faa4c2d531',
    messagingSenderId: '375357259172',
    projectId: 'flutter-practice-bb455',
    authDomain: 'flutter-practice-bb455.firebaseapp.com',
    storageBucket: 'flutter-practice-bb455.appspot.com',
    measurementId: 'G-GMGRPF6R2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9A--_jSPpQiE85FLRjR7k371Vr3f9ag',
    appId: '1:375357259172:android:7a6fe1e8c7299bc7c2d531',
    messagingSenderId: '375357259172',
    projectId: 'flutter-practice-bb455',
    storageBucket: 'flutter-practice-bb455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxBgKz_UW2nMj01J_VG6JzE3PO6qOWuY',
    appId: '1:375357259172:ios:de7a7f90ee849dc3c2d531',
    messagingSenderId: '375357259172',
    projectId: 'flutter-practice-bb455',
    storageBucket: 'flutter-practice-bb455.appspot.com',
    iosBundleId: 'com.example.flatterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxBgKz_UW2nMj01J_VG6JzE3PO6qOWuY',
    appId: '1:375357259172:ios:79450f866b8ed09bc2d531',
    messagingSenderId: '375357259172',
    projectId: 'flutter-practice-bb455',
    storageBucket: 'flutter-practice-bb455.appspot.com',
    iosBundleId: 'com.example.flatterProject.RunnerTests',
  );
}
